# Generated by Django 3.2.19 on 2023-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_story_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='like',
            field=models.ManyToManyField(to='users.story'),
        ),
    ]
