# Generated by Django 3.2.19 on 2023-07-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desс', models.TextField(blank=True, verbose_name='основная информация')),
                ('image', models.ImageField(blank=True, upload_to='static\\media\\img')),
            ],
            options={
                'verbose_name': 'МУЖСКОЙ сторис',
                'verbose_name_plural': 'МУЖИТСКИЕ сторисы',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='storys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.story'),
        ),
    ]
