# Generated by Django 3.2.19 on 2023-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='storys',
        ),
    ]
