# Generated by Django 3.2.19 on 2023-07-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_amount',
            field=models.IntegerField(default='0'),
        ),
    ]
